# Generated by Django 6.0.6 on 2026-06-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_colaborador_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('avaria', models.CharField(max_length=200)),
                ('preco_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('imagem_produto', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_retirada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente (Aguardando Retirada)'), ('Retirado', 'Retirado (Finalizado)'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
    ]
