# Generated by Django 6.0.6 on 2026-06-23 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_produto_pedido_data_retirada_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='limite_por_funcionario',
            field=models.PositiveIntegerField(default=1, help_text='Limite de compras a cada 24 horas por funcionário.'),
        ),
    ]
