# Generated by Django 6.0.6 on 2026-06-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_itempedido_produto_produto_limite_por_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
