# Generated by Django 6.0.6 on 2026-06-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_colaborador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_rh',
            field=models.BooleanField(default=False, help_text='Designa se este usuário tem acesso ao Relatório do RH.'),
        ),
    ]
