# Generated by Django 6.0.6 on 2026-06-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_userprofile_is_rh'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descontado_rh',
            field=models.BooleanField(default=False, help_text='Verdadeiro se o RH já deu baixa na folha de pagamento.'),
        ),
    ]
