# Generated by Django 6.0.6 on 2026-07-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_pedido_responsavel_retirada'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do colaborador (com ou sem pontuação)', max_length=14, null=True),
        ),
    ]
