# Generated by Django 6.0.6 on 2026-07-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_colaborador_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='email',
        ),
    ]
