# Generated by Django 6.0.6 on 2026-07-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_remove_colaborador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='limite_por_funcionario',
            field=models.PositiveIntegerField(default=1, help_text='Limite de compras por funcionário por ciclo de folha (até o RH dar baixa).'),
        ),
    ]
