# Generated by Django 6.0.6 on 2026-07-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_produto_limite_por_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_ads',
            field=models.CharField(blank=True, help_text='Código ADS utilizado pelo RH durante a baixa.', max_length=5, null=True),
        ),
    ]
