# Generated by Django 6.0.7 on 2026-07-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_pedido_codigo_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='local_retirada',
            field=models.CharField(choices=[('Brasília', 'Brasília'), ('Goiânia', 'Goiânia')], default='Brasília', max_length=20),
        ),
    ]
