# Generated by Django 6.0.7 on 2026-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_pedido_local_retirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente (Em preparo)'), ('Enviado', 'Enviado para Filial'), ('Pronto', 'Pronto para Retirada'), ('Retirado', 'Retirado (Finalizado)'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
    ]
