# Generated by Django 6.0.7 on 2026-07-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
